### ISSUE TITLE
Version 3.2.8: Invalid option -FS: unknown option

### ISSUE THREAD

**Issue by AlterDepp** [deftwork/samba#22]
When I try to start a docker-image version 3.2.8, the container stopps with the error message
`Invalid option -FS: unknown option` Version 3.2.7 works fine.

**Comment by wjiec** [comment]
same problem here

**Comment by cybermcm** [comment]
Raspberry Pi, uname: `Linux xxx 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`
same here

**Comment by elswork** [comment]
Hi @AlterDepp, @wjiec, @cybermcm 

Thanks for your help, I've removed option "S" and pushed again 3.2.8 to Docker Hub Repository.
Ensure to delete 3.2.8 on your local and/or pull again from registry.
