### ISSUE TITLE
Please add a docker-compose example in the readme

### ISSUE THREAD

**Issue by alexrtou** [deftwork/samba#4]
I use your docker on my pi4. great job !
But i lose some time to find the best configuration for my docker compose. I purpose you an example that can be useful :)

    version: '3.7'
    networks: 
    internal:
    samba:
        image: elswork/samba
        container_name: samba
        hostname: samba
        networks: 
            - internal
        ports:
            - 139:139
            - 445:445
        volumes:
            - /MY/LOCAL/SHARED:/shared
        command: '-u "myuser:abetterpasswd" -s "SHARED:/shared:rw:myuser"'

for smb://your-host/shared

**Comment by elswork** [comment]
Thanks for the suggestion!
Here is an example of a docker-compose file:
[docker-compose.yml](https://github.com/deftwork/samba/blob/master/docker-compose.yml)
