### ISSUE TITLE
users don't have write rights :(

### ISSUE THREAD

**Issue by nicedevil007** [deftwork/samba#5]
Hey folks,

I have a problem that all my users don't have write rights to the shares :(

So maybe I just don't understand correct how I have to create the users.
Is it mandatory that the user exists on the host with the same username and userid or is this just needed for the container?
Also the share on the host should have the same username/id as the owner of the directory or not?

```
docker run -d -p 445:445 \
  -- hostname any-host-name \ # Optional
  -e TZ=Europe/Madrid \ # Optional
  -v /any/path:/share/data \ # Replace /any/path with some path in your system owned by a real user from your host filesystem
  elswork/samba \
  -u "1000:1000:alice:alice:put-any-password-here" \ # At least the first user must match (password can be different) with a real user from your host filesystem
  -u "1001:1001:bob:bob:secret" \
  -u "1002:1002:guest:guest:guest" \
  -s "Backup directory:/share/backups:rw:alice,bob" \ 
  -s "Alice (private):/share/data/alice:rw:alice" \
  -s "Bob (private):/share/data/bob:rw:bob" \
  -s "Documents (readonly):/share/data/documents:ro:guest,alice,bob"

```

**Comment by elswork** [comment]
At least the first user (alice) must match (password can be different) with a real user from your host filesystem with access to the shared folder.
