### ISSUE TITLE
Add user 'xxxx' addgroup: group 'xxxx' in use

### ISSUE THREAD

**Issue by lubbifo** [deftwork/samba#6]
If I start the container using `docker run ... ` everything works fine. If I then stop and restart the container, I get 

`Add user 'xxxx' addgroup: group 'xxxx' in use`

a couple times and the container quits. Could this be caused by the variable FIRSTTIME in entrypoint to not being stored in the container? 
Am I doing anything wrong?

**Comment by falzonv** [comment]
Hello, I was going to report the same issue which is also observed using `docker-compose`.

When creating the container the first time, everything is fine.
But then if the container is restarted for any reason (either a manual restart or an hardware reboot when there is a restart policy), it displays the same error message than reported by @lubbifo. If a restart policy is configured, the container keeps restarting and exiting with this error message.

I am not sure how variables are exactly stored in containers, but this bug might indeed be related to `FIRSTTIME`.
Maybe a safer way would be to create a file at the root of the container ?
*(if for example the file `init_done` does not exist, we know this is the first run, perform the related actions and then create the file to confirm initialization has been done)*

Finally, thank you very much for providing this great image !

Best regards.

**Comment by elswork** [comment]
I've uploaded a new version that prevents the container stop working on restart.
[Avoid create user or group if exists](https://github.com/deftwork/samba/commit/e6f6bb0cae374149de7b52256427f6d4b479c9f2)
Thanks for advising!

**Comment by falzonv** [comment]
Hello,
Thank you for the quick correction !
I confirm it solved the issue on my side :-)
Best regards.
