### ISSUE TITLE
do_connect: Connection to localhost failed (Error NT_STATUS_IO_TIMEOUT)

### ISSUE THREAD

**Issue by git-clone** [deftwork/samba#7]
I updated today and I am getting an error on the health check

`do_connect: Connection to localhost failed (Error NT_STATUS_IO_TIMEOUT)`
 
Host is RPi4.

Could be related to an issue with libseccomp2 that has affected other containers on RPi4.

[https://github.com/visibilityspots/dockerfile-cloudflared/issues/30](url)
[https://github.com/alpinelinux/docker-alpine/issues/110](url)

But I am not sure ... another symptom is the container doesn't have the correct date/time

```
bash-5.1# date
Sun Jan  0 00:100:4174038  1900
```

**Comment by git-clone** [comment]
just updated again today - I still have the same issue - time to roll my sleeves up and skill up I guess :)

**Comment by VBP8501** [comment]
I also seem to have this issue on a freshly setup raspberry pi 3B running Raspbian GNU/Linux 10 (buster). The health check fails with: do_connect: Connection to localhost failed (Error NT_STATUS_IO_TIMEOUT)

I have a, also freshly setup, odroid xu4 running Ubuntu 18.04.3 LTS with exactly the same configuration and that runs this image perfectly.

**Comment by VBP8501** [comment]
This https://github.com/dperson/samba/issues/356#issuecomment-762330214 seems to fix it for me on my raspi

**Comment by elswork** [comment]
I've the same issues in my RPI4, for the moment I can only suggest to use an earlier versión, for Raspberry SBC's (elswork/samba:3.2.1)
I believe that issue would disappear in next versions, I would inform you here when a new release of this container works properly for Raspberry.

**Comment by mauroao** [comment]
I solved this problem by adding the `--privileged` flag to the `docker run` command

**Comment by mauroao** [comment]
Another solution
Worked form me (raspberry pi 4) ! 

Upload a recent libsecconp from:
https://packages.debian.org/sid/armhf/libseccomp-dev/download

Update it: 
```
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

**Comment by elswork** [comment]
As @mauroao comments, upgrading to libseccomp2 solves that issue on Raspbian.
Thanks you
